openapi: 3.1.0
info:
  title: OAuth Service API
  version: 1.0.0
  description: API for OAuth authentication and authorization services

servers:
  - url: 'http://localhost:6062/api'
    description: Local development

security:
  - bearerAuth: [ ]

tags:
  - name: AuthController
    description: Endpoints for authentication and authorization

paths:
  /auth/login:
    post:
      tags: [AuthAction]
      summary: User Login
      description: Authenticates a user and returns access and refresh tokens.
      security: [ ]
      operationId: login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
      responses:
        '200':
          description: User Successful logged In
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '500':
          $ref: '#/components/responses/InternalServerError'
        default:
          $ref: '#/components/responses/DefaultError'


  /auth/refresh:
    post:
      tags: [AuthAction]
      summary: Refresh Access Token
      description: Generates a new access token using a valid refresh token.
      security: [ ]
      operationId: refreshAccessToken
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RefreshTokenRequest'
      responses:
        '200':
          description: New access token generated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '500':
          $ref: '#/components/responses/InternalServerError'
        default:
          $ref: '#/components/responses/DefaultError'


  /auth/logout:
    post:
      tags: [AuthAction]
      summary: User Logout
      description: Invalidates the provided refresh token.
      operationId: logout
      security: [ ]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LogoutRequest'
      responses:
        '204':
          description: User successfully logged out
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '500':
          $ref: '#/components/responses/InternalServerError'
        default:
          $ref: '#/components/responses/DefaultError'
          

  /auth/logout-all:
    post:
      tags: [AuthAction]
      summary: Logout from All Devices
      description: Invalidates all refresh tokens for the user, logging them out from all devices.
      operationId: logoutAll
      security: [ ]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LogoutRequest'
      responses:
        '204':
          description: User successfully logged out from all devices
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '500':
          $ref: '#/components/responses/InternalServerError'
        default:
          $ref: '#/components/responses/DefaultError'



  /auth/password/reset:
    post:
      tags: [AuthAction]
      summary: Reset Password
      description: Resets the user's password using a valid token.
      security: [ ]
      operationId: resetPassword
      parameters:
        - name: token
          in: query
          description: Bearer token for authentication
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PasswordResetRequest'
      responses:
        '204':
          description: Password successfully reset
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '500':
          $ref: '#/components/responses/InternalServerError'
        default:
          $ref: '#/components/responses/DefaultError'
          
  
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      
  schemas:
    PasswordResetRequest:
      type: object
      required: [newPassword]
      properties:
        newPassword:
          type: string
          description: The new password for the user
          example: NewStr0ngP@ss!

    LoginRequest:
      type: object
      required: [username, password]
      properties:
        username:
          type: string
          format: email
          pattern: "^(?=.{1,64}@)[A-Za-z0-9_-]+(\\.[A-Za-z0-9_-]+)*@[^-][A-Za-z0-9-]+(\\.[A-Za-z0-9-]+)*(\\.[A-Za-z]{2,})$"
          description: The user's username
          example: john.doe@email.com
        password:
          type: string
          description: The user's password
          example: StrongP@ssw0rd!

    TokenResponse:
      type: object
      required: [accessToken, refreshToken, expiresIn]
      properties:
        accessToken:
          type: string
          description: The JWT access token
          example: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJqb2huLmRvZUBlbWFpbC5jb20iLCJyb2xlcyI6W3siYXV0aG9yaXR5IjoiVVNFUiJ9XSwiaWF0IjoxNzY5OTc0NzU0LCJleHAiOjE3NzAwNjExNTR9._JOLH6BcE_fduth4bbAkC9nfggBGK0qDeGFuLei6Pw4"
        refreshToken:
          type: string
          description: The refresh token string
          example: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJqb2huLmRvZUBlbWFpbC5jb20iLCJyb2xlcyI6W3siYXV0aG9yaXR5IjoiVVNFUiJ9XSwiaWF0IjoxNzY5OTc0NzU0LCJleHAiOjE3NzAwNjExNTR9._JOLH6BcE_fduth4bbAkC9nfggBGK0qDeGFuLei6Pw4"
        expiresIn:
          type: integer
          description: Expiration time of the access token in seconds
          example: 3600

    LogoutRequest:
      type: object
      required: [refreshToken]
      properties:
        refreshToken:
          type: string
          description: The refresh token to be invalidated
          example: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJqb2huLmRvZUBlbWFpbC5jb20iLCJyb2xlcyI6W3siYXV0aG9yaXR5IjoiVVNFUiJ9XSwiaWF0IjoxNzY5OTc0NzU0LCJleHAiOjE3NzAwNjExNTR9._JOLH6BcE_fduth4bbAkC9nfggBGK0qDeGFuLei6Pw4"

    RefreshTokenRequest:
      type: object
      required: [refreshToken]
      properties:
        refreshToken:
          type: string
          description: The refresh token used to obtain a new access token
          example: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJqb2huLmRvZUBlbWFpbC5jb20iLCJyb2xlcyI6W3siYXV0aG9yaXR5IjoiVVNFUiJ9XSwiaWF0IjoxNzY5OTc0NzU0LCJleHAiOjE3NzAwNjExNTR9._JOLH6BcE_fduth4bbAkC9nfggBGK0qDeGFuLei6Pw4"

    Error:
      type: object
      required: [timestamp, status, message, path]
      properties:
        timestamp:
          type: string
          format: date-time
          example: '2023-01-01T12:00:00Z'
        status:
          type: integer
          example: 400
        path:
          type: string
          example: /api/to/path
        message:
          type: string
          example: An unexpected error occurred
        errors:
          type: object
          description: Field-specific errors
          additionalProperties:
            type: object


  responses:
    Unauthorized:
      description: Unauthorized Access
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            timestamp: '2023-01-01T12:00:00Z'
            status: 401
            error: 'Unauthorized'
            message: 'Access token is missing or invalid'


    InternalServerError:
      description: Internal Server Error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            timestamp: '2023-01-01T12:00:00Z'
            status: 500
            error: 'Internal Server Error'
            message: 'An unexpected error occurred while processing the request'


    DefaultError:
      description: Default error response
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            timestamp: '2023-01-01T12:00:00Z'
            status: 500
            error: 'Internal Server Error'
            message: 'An unexpected error occurred'


    BadRequest:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            timestamp: '2023-01-01T12:00:00Z'
            status: 400
            error: 'Bad Request'
            message: 'The request was invalid or cannot be served'
            fieldErrors:
              firstname: 'First name is required'
              email: 'Email format is invalid'